/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */

syntax = "proto3";
package org.opensearch.protobufs.services;

option java_multiple_files = true;
option java_package = "org.opensearch.protobufs.services";
option java_outer_classname = "DocumentServiceProto";
option go_package = "github.com/romanchechyotkin/syncgo/internal/pb/opensearchpb";

import "schemas/common.proto";

service DocumentService {
  // Bulk add, update, or delete multiple documents in a single request.
  rpc Bulk(BulkRequest) returns (BulkResponse) {}
  
}
