postgresql:
  user: pglogrepl
  password: secret
  host: localhost
  port: 5432
  database: pglogrepl
# Use either elasticsearch or opensearch (exactly one required)
search_engine:
  name: elasticsearch
  addresses:
    - http://localhost:9200
  username: admin
  password: Es123456
  index: test_index
  # optional: use gRPC for bulk instead of HTTP only with opensearch
  # grpc:
  #   host: localhost
  #   port: 50051
metrics:
  port: 9090  # set to 0 to disable
