// Code generated by MockGen. DO NOT EDIT.
// Source: batcher.go
//
// Generated by this command:
//
//	mockgen -source=batcher.go -destination=./mocks/bulk_sender_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	bulk_transformer "github.com/syncgo/syncgo/internal/bulk_transformer"
	gomock "go.uber.org/mock/gomock"
)

// MockBulkSender is a mock of BulkSender interface.
type MockBulkSender struct {
	ctrl     *gomock.Controller
	recorder *MockBulkSenderMockRecorder
	isgomock struct{}
}

// MockBulkSenderMockRecorder is the mock recorder for MockBulkSender.
type MockBulkSenderMockRecorder struct {
	mock *MockBulkSender
}

// NewMockBulkSender creates a new mock instance.
func NewMockBulkSender(ctrl *gomock.Controller) *MockBulkSender {
	mock := &MockBulkSender{ctrl: ctrl}
	mock.recorder = &MockBulkSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBulkSender) EXPECT() *MockBulkSenderMockRecorder {
	return m.recorder
}

// Bulk mocks base method.
func (m *MockBulkSender) Bulk(ctx context.Context, data bulk_transformer.DataPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bulk", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Bulk indicates an expected call of Bulk.
func (mr *MockBulkSenderMockRecorder) Bulk(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bulk", reflect.TypeOf((*MockBulkSender)(nil).Bulk), ctx, data)
}
