// Code generated by MockGen. DO NOT EDIT.
// Source: batcher.go
//
// Generated by this command:
//
//	mockgen -source=batcher.go -destination=./mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	bulk_transformer "github.com/syncgo/syncgo/internal/bulk_transformer"
	gomock "go.uber.org/mock/gomock"
)

// MockBulkSender is a mock of BulkSender interface.
type MockBulkSender struct {
	ctrl     *gomock.Controller
	recorder *MockBulkSenderMockRecorder
	isgomock struct{}
}

// MockBulkSenderMockRecorder is the mock recorder for MockBulkSender.
type MockBulkSenderMockRecorder struct {
	mock *MockBulkSender
}

// NewMockBulkSender creates a new mock instance.
func NewMockBulkSender(ctrl *gomock.Controller) *MockBulkSender {
	mock := &MockBulkSender{ctrl: ctrl}
	mock.recorder = &MockBulkSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBulkSender) EXPECT() *MockBulkSenderMockRecorder {
	return m.recorder
}

// Bulk mocks base method.
func (m *MockBulkSender) Bulk(ctx context.Context, data bulk_transformer.DataPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bulk", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Bulk indicates an expected call of Bulk.
func (mr *MockBulkSenderMockRecorder) Bulk(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bulk", reflect.TypeOf((*MockBulkSender)(nil).Bulk), ctx, data)
}

// MockFlushMonitoring is a mock of FlushMonitoring interface.
type MockFlushMonitoring struct {
	ctrl     *gomock.Controller
	recorder *MockFlushMonitoringMockRecorder
	isgomock struct{}
}

// MockFlushMonitoringMockRecorder is the mock recorder for MockFlushMonitoring.
type MockFlushMonitoringMockRecorder struct {
	mock *MockFlushMonitoring
}

// NewMockFlushMonitoring creates a new mock instance.
func NewMockFlushMonitoring(ctrl *gomock.Controller) *MockFlushMonitoring {
	mock := &MockFlushMonitoring{ctrl: ctrl}
	mock.recorder = &MockFlushMonitoringMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlushMonitoring) EXPECT() *MockFlushMonitoringMockRecorder {
	return m.recorder
}

// IncFlushFailure mocks base method.
func (m *MockFlushMonitoring) IncFlushFailure() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncFlushFailure")
}

// IncFlushFailure indicates an expected call of IncFlushFailure.
func (mr *MockFlushMonitoringMockRecorder) IncFlushFailure() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncFlushFailure", reflect.TypeOf((*MockFlushMonitoring)(nil).IncFlushFailure))
}

// IncFlushRetry mocks base method.
func (m *MockFlushMonitoring) IncFlushRetry() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncFlushRetry")
}

// IncFlushRetry indicates an expected call of IncFlushRetry.
func (mr *MockFlushMonitoringMockRecorder) IncFlushRetry() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncFlushRetry", reflect.TypeOf((*MockFlushMonitoring)(nil).IncFlushRetry))
}

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
	isgomock struct{}
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// SetBatcherBufferSize mocks base method.
func (m *MockMetrics) SetBatcherBufferSize(n int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBatcherBufferSize", n)
}

// SetBatcherBufferSize indicates an expected call of SetBatcherBufferSize.
func (mr *MockMetricsMockRecorder) SetBatcherBufferSize(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBatcherBufferSize", reflect.TypeOf((*MockMetrics)(nil).SetBatcherBufferSize), n)
}
