postgresql:
  user: pglogrepl
  password: secret
  host: localhost
  port: 5432
  database: pglogrepl
search_engine:
  name: opensearch
  address: http://localhost:9300
  username: admin
  password: Op3nS3arch!
  index: test_index
batcher:
  size: 100
  flush_interval: 50ms
