postgresql:
  user: postgres
  password: postgres
  host: localhost
  port: 5432
  database: postgres
  slot_name: test_slot
  publication_name: test_publication
search_engine:
  name: opensearch
  address: http://localhost:9300
  username: admin
  password: Op3nS3arch!
  index: test_index
batcher:
  size: 100
  flush_interval: 50ms
