//
// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.
//
// Modifications Copyright OpenSearch Contributors. See
// GitHub history for details.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: services/document_service.proto

package opensearchpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_services_document_service_proto protoreflect.FileDescriptor

const file_services_document_service_proto_rawDesc = "" +
	"\n" +
	"\x1fservices/document_service.proto\x12!org.opensearch.protobufs.services\x1a\x14schemas/common.proto2j\n" +
	"\x0fDocumentService\x12W\n" +
	"\x04Bulk\x12%.org.opensearch.protobufs.BulkRequest\x1a&.org.opensearch.protobufs.BulkResponse\"\x00Bx\n" +
	"!org.opensearch.protobufs.servicesB\x14DocumentServiceProtoP\x01Z;github.com/romanchechyotkin/syncgo/internal/pb/opensearchpbb\x06proto3"

var file_services_document_service_proto_goTypes = []any{
	(*BulkRequest)(nil),  // 0: org.opensearch.protobufs.BulkRequest
	(*BulkResponse)(nil), // 1: org.opensearch.protobufs.BulkResponse
}
var file_services_document_service_proto_depIdxs = []int32{
	0, // 0: org.opensearch.protobufs.services.DocumentService.Bulk:input_type -> org.opensearch.protobufs.BulkRequest
	1, // 1: org.opensearch.protobufs.services.DocumentService.Bulk:output_type -> org.opensearch.protobufs.BulkResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_document_service_proto_init() }
func file_services_document_service_proto_init() {
	if File_services_document_service_proto != nil {
		return
	}
	file_schemas_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_document_service_proto_rawDesc), len(file_services_document_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_document_service_proto_goTypes,
		DependencyIndexes: file_services_document_service_proto_depIdxs,
	}.Build()
	File_services_document_service_proto = out.File
	file_services_document_service_proto_goTypes = nil
	file_services_document_service_proto_depIdxs = nil
}
