// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=./mocks/monitoring_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMonitoring is a mock of Monitoring interface.
type MockMonitoring struct {
	ctrl     *gomock.Controller
	recorder *MockMonitoringMockRecorder
	isgomock struct{}
}

// MockMonitoringMockRecorder is the mock recorder for MockMonitoring.
type MockMonitoringMockRecorder struct {
	mock *MockMonitoring
}

// NewMockMonitoring creates a new mock instance.
func NewMockMonitoring(ctrl *gomock.Controller) *MockMonitoring {
	mock := &MockMonitoring{ctrl: ctrl}
	mock.recorder = &MockMonitoringMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMonitoring) EXPECT() *MockMonitoringMockRecorder {
	return m.recorder
}

// AddSearchErrors mocks base method.
func (m *MockMonitoring) AddSearchErrors(backend string, errorsCount float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddSearchErrors", backend, errorsCount)
}

// AddSearchErrors indicates an expected call of AddSearchErrors.
func (mr *MockMonitoringMockRecorder) AddSearchErrors(backend, errorsCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSearchErrors", reflect.TypeOf((*MockMonitoring)(nil).AddSearchErrors), backend, errorsCount)
}

// IncSearchRequests mocks base method.
func (m *MockMonitoring) IncSearchRequests(backend, status string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncSearchRequests", backend, status)
}

// IncSearchRequests indicates an expected call of IncSearchRequests.
func (mr *MockMonitoringMockRecorder) IncSearchRequests(backend, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncSearchRequests", reflect.TypeOf((*MockMonitoring)(nil).IncSearchRequests), backend, status)
}

// ObserveSearchBulkDuration mocks base method.
func (m *MockMonitoring) ObserveSearchBulkDuration(backend, status string, seconds float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveSearchBulkDuration", backend, status, seconds)
}

// ObserveSearchBulkDuration indicates an expected call of ObserveSearchBulkDuration.
func (mr *MockMonitoringMockRecorder) ObserveSearchBulkDuration(backend, status, seconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveSearchBulkDuration", reflect.TypeOf((*MockMonitoring)(nil).ObserveSearchBulkDuration), backend, status, seconds)
}
